blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/',
             views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search')
]

django_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {'post':PostSitemap}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

#Добавляем свой менеджер (пока что просто так)
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published') #Фильтр по умолчанию по опубликованным статьям

class Post(models.Model):
    objects = models.Manager() #Это мнеджер по умолчанию
    published = PublishedManager() # А это самоельный менеджер выше
    #Post.published.filter(title__startswith='Who') Т.е. при выполнении этой команды мы получим не только статьи, начинающиеся на Who, но и опубликованные
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day,
                                                 self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments') #Чтобы обратиться не comment_set, a comment
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True) # Чтобы можно было скрыть коммент(непреемлемый, например)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Кометарий {} к статье {}'

# class Comment(models.Model):
#     post = models.ForeignKey(Post,
#                              on_delete=models.CASCADE,
#                              related_name='comments')
#     name = models.CharField(max_length=80)
#     email = models.EmailField()
#     body = models.TextField()
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     active = models.BooleanField(default=True)
#
#     class Meta:
#         ordering = ('created',)
#
#     def __str__(self):
#         return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from .models import Comment

#Создадим класс формы, унаследованный от встроенного базавого класса Django стандартных форм Form
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='Ваше имя')
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea) #Заменили стандартный input на <text-area>

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body') #Определяем какие поля модели используем

class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from taggit.models import Tag
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank #Последние два позволяют ранжировать выдачу
from django.contrib.postgres.search import TrigramSimilarity

def post_list(request, tag_slug=None):
    #posts = Post.published.all() #Используем свой менеджер
    object_list = Post.published.all()
    tag=None

    if tag_slug:
        tag = get_object_or_404(Tag, tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page':page, 'posts':posts, 'tag':tag})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

def post_detail(request, year, month, day, post):
    post =get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids) \
            .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post':post,
                                                     'comments':comments,
                                                     'new_comment':new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts':similar_posts})

def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published') #Получение статьи по id
    sent = False
    if request.method == 'POST':
        form = EmailPostForm(request.POST) #Отправка формы на сохранение
        if form.is_valid(): # Если все поля корректно заполнены, то сохраняем форму
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) рекомендую крутые статьи "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Прочесть "{}" можно здесь {}\n\n{} прокомментировал:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'vetalboy94@gmail.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post':post, 'form':form, 'sent':sent})

def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
    if form.is_valid():
        query = form.cleaned_data['query']
        search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
        search_query = SearchQuery(query)
        results = Post.objects.annotate(
            similarity=TrigramSimilarity('title', query),
        ).filter(similarity__gt=0.3).order_by('-similarity')
        # results = Post.objects.annotate(
        #     search=search_vector,
        #     rank=SearchRank(search_vector, search_query)
        # ).filter(rank__gte=0.3).order_by('-rank') #Отображаем ранжированные статьи с весом более 0,3
        # Простой вариант
        # results = Post.objects.annotate(
        #     search=SearchVector('title', 'body'),
        # ).filter(search=query)
    return render(request, 'blog/post/search.html', {'form':form,
                                                     'query':query,
                                                     'results':results})

blog/templates/blog/post/detail.html
{#{% extends "blog/base.html" %}#}
{##}
{#{% block title %}{{ post.title }}{% endblock %}#}
{##}
{#{% block content %}#}
{#  <h1>{{ post.title }}</h1>#}
{##}
{#  <p class="date">#}
{#    Published {{ post.publish }} by {{ post.author }}#}
{#  </p>#}
{#  {{ post.body|linebreaks }}#}
{#  <p>#}
{#    <a href="{% url "blog:post_share" post.id %}">#}
{#      Share this post#}
{#    </a>#}
{#  </p>#}
{##}
{#  <h2>Similar posts</h2>#}
{#  {% for post in similar_posts %}#}
{#    <p>#}
{#      <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>#}
{#    </p>#}
{#  {% empty %}#}
{#    There are no similar posts yet.#}
{#  {% endfor %}#}
{##}
{#  {% with comments.count as total_comments %}#}
{#    <h2>#}
{#      {{ total_comments }} comment{{ total_comments|pluralize }}#}
{#    </h2>#}
{#  {% endwith %}#}
{#  {% for comment in comments %}#}
{#    <div class="comment">#}
{#      <p class="info">#}
{#        Comment {{ forloop.counter }} by {{ comment.name }}#}
{#        {{ comment.created }}#}
{#      </p>#}
{#      {{ comment.body|linebreaks }}#}
{#    </div>#}
{#  {% empty %}#}
{#    <p>There are no comments yet.</p>#}
{#  {% endfor %}#}
{##}
{#  {% if new_comment %}#}
{#    <h2>Your comment has been added.</h2>#}
{#  {% else %}#}
{#    <h2>Add a new comment</h2>#}
{#    <form action="." method="post">#}
{#      {{ comment_form.as_p }}#}
{#      {% csrf_token %}#}
{#      <p><input type="submit" value="Add comment"></p>#}
{#    </form>#}
{#  {% endif %}#}
{#{% endblock %}#}


{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title}}
        Published {{ post.publish }} by {{ post.author }}
    </h1>
    {{ post.body|markdown }}
    <p>
        <a href="{% url "blog:post_share" post.id %}">Поделиться статьёй</a>
    </p>
    {% with comments.count as total_comments %}
{#        Pluralize используется для написания слова во множественном числе (встроено в django)#}
        <h2>{{ total_comments }}Комментарий {{ total_comments|pluralize }}</h2>
    {% endwith %}
    <h2>Рекомендуем</h2>
      {% for post in similar_posts %}
        <p>
          <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
      {% empty %}
        There are no similar posts yet.
      {% endfor %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                {{ forloop.counter }}-й коментарий:  "{{ comment.name }}"
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>Нет ни одного комментария. Будьте первым!</p>
    {% endfor %}
    {% if new_comment %}
        <h2>Ваш комментарий был добавлен. </h2>
    {% else %}
        <h2>Добавить новый комментарий</h2>
        <form action="." method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить комментарий"></p>
        </form>
    {% endif %}
{% endblock %}


{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

blog/templates/blog/post/latest_posts.html
<!DOCTYPE html>
<html lang="en">
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
<body>

<ul>
    {% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a> </li>
    {% endfor %}
</ul>

</body>
</html>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}

{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
      <h2>Метка {{ tag.name }}</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
     <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}">
            {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
        {% endfor %}
     </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
{#    {{ post.body|truncatewords:30|linebreaks }}#}
{#      #Обрезает строку по количеству символов#}
      {{ post.body|markdown|truncatewords_html:30 }}
  {% endfor %}
  {% include "pagination.html" with page=posts %}
{% endblock %}


{#{% extends "blog/base.html" %}#}
{##}
{#{% block title %}My Blog{% endblock %}#}
{##}
{#{% block content %}#}
{#  <h1>My Blog</h1>#}
{#  {% if tag %}#}
{#    <h2>Posts tagged with "{{ tag.name }}"</h2>#}
{#  {% endif %}#}
{#  {% for post in posts %}#}
{#    <h2>#}
{#      <a href="{{ post.get_absolute_url }}">#}
{#        {{ post.title }}#}
{#      </a>#}
{#    </h2>#}
{#    <p class="tags">#}
{#      Tags:#}
{#      {% for tag in post.tags.all %}#}
{#        <a href="{% url "blog:post_list_by_tag" tag.slug %}">#}
{#          {{ tag.name }}#}
{#        </a>#}
{#        {% if not forloop.last %}, {% endif %}#}
{#      {% endfor %}#}
{#    </p>#}
{#    <p class="date">#}
{#      Published {{ post.publish }} by {{ post.author }}#}
{#    </p>#}
{#    {{ post.body|truncatewords:30|linebreaks }}#}
{#  {% endfor %}#}
{#  {% include "pagination.html" with page=posts %}#}
{#{% endblock %}#}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block title %}Search{% endblock %}
{% block content %}
{% if query %}
<h1>Статья содержит "{{ query }}"</h1>
<h3>
{% with results.count as total_results %}
Всего статей найдего по вашему запросу {{ total_results }} {{ total_results|pluralize }}
{% endwith %}
</h3>
{% for post in results %}
<h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
{{ post.body|truncatewords:5 }}
{% empty %}
<p>По вашему запросу ничего не найдено.</p>
{% endfor %}
<p><a href="{% url "blog:post_search" %}">Искать снова</a></p>
{% else %}
<h1>Поиск статей</h1>
<form action="." method="get">
{{ form.as_p }}
<input type="submit" value="Search">
</form>
{% endif %}
{% endblock %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}

blog/templates/blog/post/share.html
{#{% extends "blog/base.html" %}#}
{##}
{#{% block title %}Поделиться статьёй{% endblock %}#}
{##}
{#{% block content %}#}
{#  {% if sent %}#}
{#    <h1>E-mail successfully sent</h1>#}
{#    <p>#}
{#      "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.#}
{#    </p>#}
{#  {% else %}#}
{#    <h1>Share "{{ post.title }}" by e-mail</h1>#}
{#    <form action="." method="post">#}
{#      {{ form.as_p }}#}
{#      {% csrf_token %}#}
{#      <input type="submit" value="Send e-mail">#}
{#    </form>#}
{#  {% endif %}#}
{#{% endblock %}#}

{% extends "blog/base.html" %}
{% block title %}Поделиться постом{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Письмо успешно доставлено</h1>
        <p>"{{ post.title }}" отправлена {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Отправка  "{{ post.title }}" по почте</h1>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить письмо">
        </form>
    {% endif %}
{% endblock %}

{##}
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>Title</title>#}
{#</head>#}
{#<body>#}
{##}
{#</body>#}
{#</html>#}